name: CI

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: PyDK Android build
      run: |
            python3 -V
            echo
            clang --version | head -n 1
            echo
            gcc --version | head -n 1
            echo
            grep "^Pkg.Revision =" ${ANDROID_HOME}/ndk-bundle/source.properties
            echo
            sudo apt-get install python3-venv >/dev/null 2>&1
            pwd
            ls -al
            ARCHITECTURES=hostonly time pydk-android-all.sh
            cd /home/runner/work/pydk/pydk
            ARCHITECTURES=armeabi-v7a time pydk-android-all.sh
            cd /home/runner/work/pydk/pydk
            ARCHITECTURES=arm64-v8a time pydk-android-all.sh
            cd /home/runner/work/pydk/pydk
            ARCHITECTURES=x86  time pydk-android-all.sh
            cd /home/runner/work/pydk/pydk
            ARCHITECTURES=x86_64 time pydk-android-all.sh"
