name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get Python2 version
      run: python -V
    - name: Run a multi-line script
      run: |
        echo ---------------------
        python3 -V
        clang --version
        gcc --version
        env
