name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Prepare PyDK Android build
      run: |
        echo ---------------------
        python3 -V
        echo
        clang --version | head -n 1
        echo
        gcc --version | head -n 1
        echo
        env|grep ANDROID
        echo
        grep "^Pkg.Revision =" ${ANDROID_HOME}/ndk-bundle/source.properties
        echo
        sudo apt-get install python3-venv
        pwd
    - name: Run PyDK Android build
      run: |
        ls -al
        time sh pydk-android-all.sh
